# -*- coding: utf-8 -*-
"""proyecto_ciencia_de_datos_isabel_gude_gomez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/isagudeg/0499be304cde50ae38071c985e9a1795/proyecto_ciencia_de_datos_isabel_gude_gomez.ipynb

En este trabajo he analizado datos sobre los mangas más vendidos a partir de 100 millones de copias.

Antes de empezar quiero aclarar que un manga es un tipo de cómic de origen japonés y de estética generalmente sencilla.

En primer lugar, descargamos el documento con el que vamos a trabajar. En este caso es un documento tipo csv.

El documento original pertenece a wikipedia ([Mangas más vendidos](https://)), pero el que estamos usando está subido a mi repositorio "cosas de clase" en mi cuenta de github.
"""

!wget https://raw.githubusercontent.com/isagudeg/cosas-de-clase/main/mangas_mas_vendidos_a_partir_de_100_millones_de_copias.csv

"""A continuación tendremos que disponer de una serie de bibliotecas para realizar el analisis de los datos y sus correspondientes representaciones gráficas."""

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.dates as mdates

"""El primer paso para empezar a trabajar con nuestros datos es descargarnos nuestro documento a través de la librería Pandas, con la que podremos realizar una lectura a nuestra tabla."""

mangas = pd.read_csv('mangas_mas_vendidos_a_partir_de_100_millones_de_copias.csv')
print(mangas)

"""Antes de realizar algún tipo de operación en el documento hay que hacer una limpieza de los datos. En mi caso he eliminado las columnas con el nombre del autor, su serialización y el número correspondiente al top en base a sus ventas, ya que no voy a trabajar con estos.

A continuación he renombrado la columna "Serie de manga" por "Nombre" y "Editor" por "Editorial" para facilitar la comprensión de los datos a trabajar.
"""

mangas.rename(columns={"Serie de manga": "Nombre", "Editor": "Editorial"}, inplace=True)
mangas.drop(["Autor(es)", "Serializado","#"], axis=1, inplace=True)
print(mangas)

"""Tras la limpieza, podremos comenzar a operar. En mi caso he creado una nueva columna en la cual he calculado el porcentaje de ventas de cada manga tomando One Piece (OP), que es el que cuenta con las mayores ventas, como el 100%.

Esto lo he hecho ya que, de esta forma, podemos ver la diferencia en las ventas entre unas obras y otras mucho más fácil.
"""

OP = mangas["Ventas aproximadas en millones"]
mangas["Porcentaje de ventas en base al mayor"] = round(mangas.loc[:,"Ventas aproximadas en millones"]*100/OP[0],2)
print(mangas)

"""Una vez hayamos terminado con la limpieza y los cálculos ya podemos comenzar a representar gráficamente todos nuestros datos:

Esta gráfica representa cuántos mangas han sido editados por las diferentes editoriales, de esta forma podemos ver claramente cómo la editorial con el mayor éxito en cuanto a publicaciones es Shueisha, seguida de Shogakukan y Kodansha.
"""

mangas.groupby("Editorial")["Nombre"].count().plot(kind='bar', color= "hotpink")

"""Esta gráfica nos relaciona las editoriales y las ventas, y en ella podemos comprobar como la editorial con el mayor éxito, Shueisha, es también la que genera una mayor ganancia, aunque esto podría haberse ya deducido a través de la gráfica anterior."""

fig = plt.figure(figsize=(5, 5))
plt.ylabel("Ventas aproximadas en millones", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Editorial", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.bar(mangas["Editorial"], mangas["Ventas aproximadas en millones"],color = "hotpink")
plt.grid(alpha=0.3)
plt.xticks(rotation = 30)
plt.show()

"""Esta gráfica es similar a la primera, solo que, en vez de analizar las editoriales, analizamos las categorías (las diferentes categorías de mangas en Japón reciben un nombre concreto, de manera que dividen su público objetivo para facilitar a los lectores la búsqueda de historias con una temática específica).

En este caso, la categoría por preferencia es el shonen (manga dirigido a un público adolescente masculino), tras esta, está el seinen (manga dirigido a hombres mayores de edad), y finalmete el kodomo (manga para niños pequeños de entre 4 y 12 años). Además vemos que hay una pequeña cantidad de obras que comparten dos categorías, shonen y seinen.
"""

mangas.groupby("Categoría")["Nombre"].count().plot(kind='bar', color= "blueviolet")

"""Al igual que antes, la siguiente gráfica nos muestra algo que podríamos haber deducido en base a la anterior, y es la relación entre categoría y ventas, ya que siendo el shonen la categoría más consumida, tambien es esta la más vendida y, por lo tanto, la que genera más dinero."""

fig = plt.figure(figsize=(5, 5))
plt.ylabel("Ventas aproximadas en millones", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Categoría", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.bar(mangas["Categoría"], mangas["Ventas aproximadas en millones"],color = "blueviolet")
plt.grid(alpha=0.3)
plt.show()

"""A continuación, para analizar de forma sencilla el número de volúmenes con los que cuenta cada obra, he realizado una gráfica de barras sencilla, de esta forma vemos que los mangas con un mayor número de volúmenes son Golgo 13 y Kochikame. Por otro lado, vemos que mangas como Black Jack y Astroboy apenas llegan a los 25 tomos aproximadamente."""

fig = plt.figure(figsize=(10, 5))
plt.ylabel("Número de volúmenes", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Nombre", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.bar(mangas["Nombre"], mangas["Volúmenes"],color = "palevioletred")
plt.grid(alpha=0.3)
plt.xticks(rotation = 90)
plt.show()

"""Esta gráfica circular representa lo mismo que la anterior, el número de volúmenes, pero en ella se puede ver de forma mucho más visual esta diferencia."""

plt.pie(mangas["Volúmenes"], labels=mangas["Nombre"])
plt.show()

"""Finalmente, tenemos la representación de las ventas, a pesar de saber que las ventas aproximadas en millones y el porcentaje de ventas en base a One Piece iban a dar la misma gráfica, decidí representarlas, ya que en la primera (gráfica de las ventas aproximadas en millones) podemos ver que el eje Y, es decir, las ventas, llega hasta más de 500. Mientras que en la segunda (gráfica del porcentaje de ventas en base al mayor), el eje Y solo llega hasta el 100, y esto puede resultarnos más útil para realizar diferentes cálculos o estimaciones.

Gracias a estas gráficas podemos ver que One Piece es, con diferencia, la obra más popular, superando casi en un 50% a Golgo 13, que es la segunda obra más vendida.
"""

fig = plt.figure(figsize=(10, 5))
plt.ylabel("Ventas aproximadas en millones", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Nombre", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.bar(mangas["Nombre"], mangas["Ventas aproximadas en millones"],color = "salmon")
plt.grid(alpha=0.3)
plt.xticks(rotation = 90)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
plt.plot(mangas["Nombre"], mangas["Ventas aproximadas en millones"], color = "salmon")
plt.grid(alpha=0.3)
plt.xticks(rotation = 90)
plt.ylabel("Ventas aproximadas en millones", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Nombre", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.show()

fig = plt.figure(figsize=(10, 5))
plt.ylabel("Porcentaje de ventas en base al mayor", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Nombre", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.bar(mangas["Nombre"], mangas["Porcentaje de ventas en base al mayor"],color = "plum")
plt.grid(alpha=0.3)
plt.xticks(rotation = 90)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
plt.plot(mangas["Nombre"], mangas["Porcentaje de ventas en base al mayor"], color = "plum")
plt.grid(alpha=0.3)
plt.xticks(rotation = 90)
plt.ylabel("Porcentaje de ventas en base al mayor", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.xlabel("Nombre", fontdict = {'fontsize':10, 'fontweight':'bold'})
plt.show()